name: 'Packages Split'

on:
  push:
    branches:
      - main
    tags:
      - '*'

env:
  # 1. for Github split
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:

  packages_split:
    runs-on: ubuntu-latest
    env:
      main_repo: 'phparm'
      package_dir: 'src'
      commit_name: 'GHJayce'
      commit_email: 'jaycedeng@outlook.com'

    strategy:
      fail-fast: false
      matrix:
        # define package to repository map
        package:
          -
            local_path: 'Entity'
            split_repository: 'entity'
          -
            local_path: 'Url'
            split_repository: 'url'

    steps:
      -   uses: actions/checkout@v2

      # no tag
      -
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: danharrin/monorepo-split-github-action@v2.4.0
        with:
          # ↓ split "packages/easy-coding-standard" directory
          package_directory: '${{ env.package_dir }}/${{ matrix.package.local_path }}'

          # ↓ into https://github.com/symplify/easy-coding-standard repository
          repository_organization: '${{ env.main_repo }}'
          repository_name: '${{ matrix.package.split_repository }}'

          # [optional, with "github.com" as default]
          #repository_host: git.private.com:1234

          # ↓ the user signed under the split commit
          user_name: '${{ env.commit_name }}'
          user_email: '${{ env.commit_email }}'

      # with tag
      -
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: danharrin/monorepo-split-github-action@v2.4.0
        with:
          tag: ${GITHUB_REF#refs/tags/}

          # ↓ split "packages/easy-coding-standard" directory
          package_directory: '${{ env.package_dir }}/${{ matrix.package.local_path }}'

          # ↓ into https://github.com/symplify/easy-coding-standard repository
          repository_organization: '${{ env.main_repo }}'
          repository_name: '${{ matrix.package.split_repository }}'

          # [optional, with "github.com" as default]
          #repository_host: git.private.com:1234

          # ↓ the user signed under the split commit
          user_name: '${{ env.commit_name }}'
          user_email: '${{ env.commit_email }}'